permalinks: title
baseurl: /python-flask
title: Websites with Python Flask
map:
 - title: Home
   path: /
   caption: Websites with Python Flask
 - title: Core
   caption: The 'mandatory' workshop content
   subpages:
    - title: Setting up
      path: /core/setup.html
      caption: Installation instructions for Windows, OSX and Linux.
    - title: Hello, World!
      path: /core/hello-world.html
      caption: Serving our first web page.
    - title: Languages of the Web
      path: /core/html-css-js.html
      caption: What the web is built on
    - title: Files & Templates
      path: /core/files-templates.html
      caption: How to serve different all the files
    - title: Forms
      path: /core/forms.html
      caption: How forms work on the web.
    - title: Form Submission
      path: /core/form-submission.html
      caption: Receiving and processing the form.
    - title: Data Structures
      path: /core/data.html
      caption: The basics of organising data in Python.
 - title: Extras
   caption: Additional workshop content
   subpages:
    - title: Learning HTML and CSS
      path: /extras/learn-html-css.html
      caption: 
    - title: Professional CSS
      path: /extras/css.html
      caption: 
    - title: Keeping track of users
      path: /extras/sessions.html
      caption: Using flask sessions
    - title: Using a database
      path: /extras/databases.html
      caption: 
    - title: Hosting on Heroku
      path: /extras/heroku.html
      caption: Host your website for free online using Heroku.
